### ISSUE TITLE
Flatpak manifest

### ISSUE THREAD

**Issue by zocker-160** [Goddard/eekeeper-qt#1]
I have created an manifest, which is kinda working, but it does complain about some missing ressources, which I do not know what that is about. Maybe you know what files it is searching for and where:

```yml
app-id: com.ryeingoddard.EEKeeperQt
runtime: org.kde.Platform
runtime-version: "5.15-21.08"
sdk: org.kde.Sdk

command: EEKeeperQt

finish-args:
    - --share=ipc
    - --socket=wayland
    - --socket=fallback-x11
    - --device=dri
    - --filesystem=home

modules:
    - name: EEKeeperQt
      buildsystem: simple
      build-commands:
        - sed -i -e "s|target.path = /|target.path = /app/lib/EEKeeper|g" EEKeeper.pro
        - qmake EEKeeper.pro
        - make -j $FLATPAK_BUILDER_N_JOBS
        - make install
      post-install:
        - mv res /app/lib/EEKeeper
        - mv ./*.o /app/lib/EEKeeper
        - mkdir -p /app/bin
        - ln -rs /app/lib/EEKeeper/EEKeeperQt /app/bin/EEKeeperQt
      sources:
        - type: git
          url: https://github.com/Goddard/eekeeper-qt.git
          commit: 05a0cfcb745576516a3927d6f004d9c975e8d0ab
```
![Screenshot_20220518_220127](https://user-images.githubusercontent.com/36563538/169145765-0844b9b3-d603-4ef8-a284-9e674df84dcb.png)
